export const MAKE_REQUEST='MAKE_REQUEST'

export const FAILED_REQUEST='FAILED_REQUEST'

export const GET_WALLET_LIST='GET_WALLET_LIST'

export const ADD_WALLET="ADD_WALLET"

export const UPDATE_WALLET="UPDATE_WALLET"

export const DELETE_WALLET="DELETE_WALLET"