//fetch data 
export const FETCH_WALLETS_REQUEST = 'FETCH_WALLETS_REQUEST';
export const FETCH_WALLETS_SUCCESS = 'FETCH_WALLETS_SUCCESS';
export const FETCH_WALLETS_FAILURE = 'FETCH_WALLETS_FAILURE';

export const CREATE_WALLETS_REQUEST = 'ADD_WALLETS_REQUEST';
export const CREATE_WALLETS_SUCCESS = 'CREATE_WALLETS_SUCCESS';
export const CREATE_WALLETS_FAILURE = 'CREATE_WALLETS_FAILED';

export const UPDATE_WALLETS_REQUEST = 'UPDATE_WALLETS_REQUEST';
export const UPDATE_WALLETS_SUCCESS = 'UPDATE_WALLETS_SUCCESS';
export const UPDATE_WALLETS_FAILURE = 'UPDATE_WALLETS_FAILED';

export const DELETE_WALLETS_REQUEST = 'DELETE_WALLETS_REQUEST';
export const DELETE_WALLETS_SUCCESS = 'DELETE_WALLETS_SUCCESS';
export const DELETE_WALLETS_FAILURE = 'DELETE_WALLETS_FAILED';

